### ISSUE TITLE
Pomifactory breaks loader

### ISSUE THREAD

**Issue by bergentroll** [pokitto/GameDisk#5]
[Pomifactory](../blob/master/2Arcade/Pomifactory.pop) deals bad. After loading there is no option to boot to loader anymore.

**Comment by pokitto** [comment]
Pomifactory was compiled with minimal PokittoLib. You can get back to loader by pressing small 'c' button when turning on Pokitto.

But yes, its behaviour is not consistent with other games. We will have to fix it

**Comment by bergentroll** [comment]
Oh, thank you, indeed.
