### ISSUE TITLE
Some demoes break loader

### ISSUE THREAD

**Issue by bergentroll** [pokitto/GameDisk#7]
This two demo fellows give no chance to come back to loader:
- [jetpack](../blob/master/7Demos/jetpack.bin)
- [intervalometer](../blob/master/7Demos/Intervalometer.bin)

In distinction to #5 this apps ignore c key on boot.

It may be frustrating on a way.

**Comment by pokitto** [comment]
Agreed. I will remove the obstinate offenders!
